# Generated by Django 5.0.6 on 2026-09-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('badge', models.CharField(blank=True, default='New Collection 2026', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('image_url_override', models.CharField(blank=True, max_length=500)),
                ('link_url', models.CharField(default='/shop/', max_length=200)),
                ('button_text', models.CharField(default='Shop Now', max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'banners',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
